### ISSUE TITLE
Metadata file contains blank lines (Windows only)

### ISSUE THREAD

**Issue by juneb** [awslabs/aws-encryption-sdk-cli#121]
aws-encryption-sdk-cli: 1.0.2.7
Windows: 10.0.14393.1884
PowerShell: 5.0.14393.1884
Related to: #65 

The metadata file that the encrypt and decrypt commands write has blank lines after each JSON string. As a result:

```
PS C:\ps-test> (cat $home\metadata.txt)[-1]
PS C:\ps-test> 
PS C:\ps-test> (cat $home\metadata.txt)[-1] -eq ''
True
```

Also, the count value is misleading:
```
PS C:\ps-test> (cat $home\metadata.txt).count
22
PS C:\ps-test> ((cat $home\metadata.txt) -match '^\S').count
11
```

**Comment by mattsb42-aws** [comment]
Yeah, I noticed this when we were doing final testing on Windows prior to release. I think that this is caused by file close behavior being different on POSIX and Windows systems, but I'll have to do some testing to verify.

**Comment by mattsb42-aws** [comment]
For future reference, after testing we discovered that the issue causing this was that when a file is opened in non-binary mode and `os.linesep` is written on a Windows platform, the `\r\n` value from `os.linesep` is intercepted by the file writer and written as `\r\r\n`.

The solution to this was to change to writing in binary mode.
